CSect   Symbol  Value   LENGTH  Flags:  
--------------------------------------
COPY            000000  000078      
        FIRST   000000          R     
        CLOOP   000006          R     
        ENDFIL  00001A          R     
        EOF     00002D          R     
        RETADR  00002E          R     
        LENGTH  000031          R     
        BUFFER  000034          R     
        RDREC   000035          R     
        RLOOP   00003F          R     
        EXIT    000055          R     
        INPUT   00005B          R     
        WRREC   00005C          R     
        WLOOP   000061          R     
        OUTPUT  000075          R     
 
Literal Table
Name  Operand Address Length: 
--------------------------------------
